{
	"name": "Hadle_Error_Rows_Pipeline",
	"properties": {
		"activities": [
			{
				"name": "Handle Error Rows",
				"type": "ExecuteDataFlow",
				"dependsOn": [],
				"policy": {
					"timeout": "0.12:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"dataflow": {
						"referenceName": "Handle Error Rows",
						"type": "DataFlowReference"
					},
					"compute": {
						"coreCount": 8,
						"computeType": "General"
					},
					"traceLevel": "Fine"
				}
			}
		],
		"annotations": [],
		"lastPublishTime": "2025-05-21T06:01:09Z"
	},
	"type": "Microsoft.DataFactory/factories/pipelines"
}